# Generated by Django 2.0.5 on 2018-05-11 17:50

import datetime
from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('image', models.FileField(blank=True, null=True, upload_to=myApp.models.upload_location)),
                ('is_original', models.BooleanField()),
                ('prod_date', models.DateField(null=True)),
                ('features', models.CharField(max_length=200)),
                ('sizes', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-id', '-created_at'],
            },
        ),
    ]
